name: Update GQM
on:
  push:
    branches: [main]
    paths:
      - "measuring/goals/**"
      - "measuring/questions/**"
      - "measuring/metrics/**"

  workflow_dispatch:

jobs:
  generateDiagram:
    name: Generate Diagram
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY_SSH_PRIVATE_KEY }}
          fetch-depth: 0
      
      - uses: actions/setup-node@v3
        with:
          node-version: "21.x"
      
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      
      - name: Update GQM diagram
        run: |
          cd scripts/gqm_gen
          ./update_gqm.sh
      
      - name: Report coverage
        if: success()
        uses: sidx1024/report-nyc-coverage-github-action@v1.2.7
        with:
          coverage_file: ".nyc_output/nyc-coverage-report/coverage-summary.json"
